services:
  web:
   build:
      context: ./frontend-job-pilot
      dockerfile: Dockerfile
   ports:
     - "3000:3000"
   working_dir: /src  
   volumes:
     - ./frontend-job-pilot:/src
     - /src/node_modules
   command: bun run dev