# node version: 22.0.0-alpine
FROM node:22.0.0-alpine

# Set the working directory inside the container
WORKDIR /src

# copy the package.json and package-lock.json files to the working directory
COPY package*.json ./

# Install production dependencies

RUN npm Install

#command to run the app
CMD ["npm", "run", "dev"]

#expose the port
EXPOSE 3000

