FROM node:22.0.0-slim

# Install Bun
RUN apt-get update && apt-get install -y curl unzip && \
    curl -fsSL https://bun.sh/install | bash && \
    ln -s /root/.bun/bin/bun /usr/local/bin/bun

WORKDIR /src

# Copy dependency files
COPY package.json package-lock.json ./

# Install deps with npm instead of bun
RUN bun install --legacy-peer-deps

# Copy the rest of the application
COPY . .

# Expose port
EXPOSE 3000

# Run dev using Bun
CMD ["bun", "run", "dev"]
