name: job-pilot

on:
  push:
    # triggers build workflow when a commit is pushed to main branch
    branches:
      - main
      # triggers development workflow when a PR is created
  pull_request:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node 
        run:  npm install
      
      - name: test
        run:  npm run test
        
      - name: build
        run:  npm run build  