name: job-pilot

on:
  push:
    branches-ignore:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node 
        run:  npm install
      
      - name: test
        run:  npm run test

      - name: build
        run:  npm run build  