name: job-pilot

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - development

jobs:
  frontend:
    name: frontend-job-pilot
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend-job-pilot

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.18.0' # or your preferred version

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Build
        run: npm run build

  backend:
    name: backend-job-pilot
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend-job-pilot

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2' # or your version

      - name: Install dependencies
        run: composer install

      - name: Run tests
        run: php artisan test

  build:
    runs-on: ubuntu-latest
    needs: [frontend, backend]

    steps:
      - name: Setup Git config
        run: |
          git config --global user.email "uttampun50@gmail.com"
          git config --global user.name "uttampun"
